"deploy-{{ACCOUNT}}":
    if: github.ref == 'refs/heads/main'
    needs: [integration-test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # Configure GitHub Action Environment to have a manual approval step before deployment to production
    # https://docs.github.com/en/actions/reference/environments
    # environment: <configured-environment>
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: actions/download-artifact@v2
        with:
          name: packaged-prod.yaml 

      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: "arn:aws:iam::{{ACCOUNT}}:role/${{inputs.pipeline_execution_role}}"
          role-session-name: prod-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to production account
        run: |
          sam deploy --stack-name ${PROD_STACK_NAME} \
            --template packaged-prod.yaml \
            --capabilities CAPABILITY_IAM \
            --region $(echo ${{env.AWS_REGION}}) \
            --s3-bucket $(echo ${{env.TESTING_ARTIFACTS_BUCKET}}) \
            --no-fail-on-empty-changeset \
            --role-arn $(echo ${{env.TESTING_CLOUDFORMATION_EXECUTION_ROLE}})





             