name: "{{ROUTE}}"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/{{ROUTE}}/**"
      - "./github/workflows/{{ROUTE}}.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  
