name: "{{ROUTE}}"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/{{ROUTE}}/**"
      - "./github/workflows/{{ROUTE}}.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  {{ACCOUNT}}-{{ROUTE}}:
    uses: ./.github/workflows/reusable-lambda-cicd.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "{{ACCOUNT}}"
      app_name: "{{ROUTE}}"

