name: {{ROUTE}}

on:
  push:
    branches:
      - main
    paths:
      - "projects/{{ROUTE}}/**"
      - ".github/workflows/{{ROUTE}}.yaml"
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::037729278610:role/github-deploy-role
          role-session-name: mysession
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      # sam build 
      - run: |- 
          cd projects/${{ROUTE}}
          sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: |-
          cd projects/${{ROUTE}}
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ROUTE}} --s3-bucket jingood2-s3-dev-content --capabilities CAPABILITY_IAM --region ap-northeast-2