name: "auth"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/auth/**"
      - "./github/workflows/auth.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  account_deploy:
    uses: ./.github/reusable-lambda-cicd.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "{{ACCOUNT}}"
      app_name: "auth"
