name: "auth"

on:
  push:
    paths:
      - "projects/auth/**"
      - ".github/workflows/auth.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd projects/auth
          go test ./...
