name: "auth"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/auth/**"
      - "./github/workflows/auth.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  
  auth-037729278610:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-lambda-cicd-v3.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "037729278610"
      stage: "dev"
      app_name: "auth"
  auth-123429278610:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-lambda-cicd-v3.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "123429278610"
      stage: "prod"
      app_name: "auth"
