name: "hello-world"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/hello-world/**"
      - "./github/workflows/hello-world.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  build-and-deploy-feature:
    # this stage is triggered only for feature branches (feature*),
    # which will build the stack and deploy to a stack named with branch name.
    #if: startsWith(github.ref, 'refs/heads/feat')
    #needs: [test]
    uses: ./.github/workflows/reusable-lambda-cicd.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "037729278610"
      app_name: hello-world

