ame: "infra"

on:
  push:
    paths:
      - "projects/infra/**"
      - ".github/workflows/infra.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd projects/infra
          go test ./...
