name: infra

on:
  push:
    branches:
      - main
    paths:
      - "projects/infra/**"
      - ".github/workflows/infra.yaml"

jobs:
  cdk_build:
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    env:
      CI: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: install npm
        run: sudo apt update -y && sudo apt install nodejs npm -y
        working-directory: projects/infra

      - name: Install dependencies
        run: npm ci
        working-directory: projects/infra

      - name: assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::037729278610:role/github-deploy-role
          role-session-name: mysession
          aws-region: ap-northeast-2

      - name: cdk diff
        run: npm run diff
        working-directory: projects/infra

      - name: cdk build 
        run: npm run build 
        working-directory: projects/infra
          
      - name: cdk deploy
        run: npm run deploy
        working-directory: projects/infra
         