name: infra

on:
  push:
    branches:
      - main
    paths:
      - "projects/infra/**"
      - ".github/workflows/infra.yaml"

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    steps:
      - name: assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::037729278610:role/github-deploy-role
          role-session-name: mysession
          aws-region: ap-northeast-2
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_version: '2.24.1'
          actions_comment: true

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.24.1'
          working_dir: 'projects/infra'