name: "infra"

on:
  push:
    branches:
      - 'main'
      - 'feat**'
    paths:
      - "projects/infra/**"
      - "./github/workflows/infra.yaml"
  delete:
    branches:
      - 'feat**'

jobs:
  infra:
    # reusable workflows MUST be in .github/workflows
    uses: ./.github/workflows/reusable-lambda-ci.yml
    permissions:
      id-token: write
      contents: read
    with:
      # 0으로 시작하는 AccountID 때문에 문자열로 명시
      aws_account_id: "037729278610"
      app_name: "infra"
