name: infra

on:
  push:
    branches:
      - main
    paths:
      - "projects/infra/**"
      - ".github/workflows/infra.yaml"

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
     # These permissions are needed to interact with GitHub's OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: projects/hello-world
          fetch-depth: 1
      - name: assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::037729278610:role/github-deploy-role
          role-session-name: mysession
          aws-region: ap-northeast-2
      - name: cdk diff
        uses: arnaskro/aws-cdk-v2-github-actions@v2.2.1
        with:
          cdk_subcommand: 'diff'