name: infra

on:
  push:
    branches:
      - main
    paths:
      - "projects/infra/**"
      - ".github/workflows/infra.yaml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::037729278610:role/github-deploy-v2-role
          role-session-name: mysession
          aws-region: ap-northeast-2
      # sam build 
      - run: |- 
          cd projects/infra
          sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: |-
          cd projects/infra
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name infra --s3-bucket jingood2-s3-dev-content --capabilities CAPABILITY_IAM --region ap-northeast-2
